[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.redis", "php82Extensions.mbstring", "php82Extensions.exif", "php82Extensions.fileinfo", "php82Extensions.bcmath", "php82Extensions.gd", "php82Extensions.openssl", "composer", "nodejs_20"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "npm install --force",
  "npm run build"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
